### ISSUE TITLE
RHEL 7.8 Support

### ISSUE THREAD

**Issue by shortspecialbus** [webtatic-rpms/php70w#3]
Hi,

RHEL 7.8 (and OL7.8) updates ImageMagick to 6.9.10.68-3.el7.x86_64 which unfortunately no longer contains libMagick*.so.5

At the very least, php70w-pecl-imagick requires the older .so.5 libraries that no longer exist.

`root: Error: Package: php70w-pecl-imagick-3.4.3-1.w7.x86_64 (@p201906-webtatic-7-64)
root:            Requires: libMagickWand.so.5()(64bit)
root:            Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@oracle-linux-latest-7-64)
root:                libMagickWand.so.5()(64bit)
root:            Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (oracle-linux-latest-7-64)
root:                Not found
root:            Available: ImageMagick-6.7.8.9-15.el7_2.x86_64 (oracle-linux-latest-7-64)
root:                libMagickWand.so.5()(64bit)
root:            Available: ImageMagick-6.7.8.9-16.el7_6.x86_64 (oracle-linux-latest-7-64)
root:                libMagickWand.so.5()(64bit)
root: Error: Package: php70w-pecl-imagick-3.4.3-1.w7.x86_64 (@p201906-webtatic-7-64)
root:            Requires: libMagickCore.so.5()(64bit)
root:            Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@oracle-linux-latest-7-64)
root:                libMagickCore.so.5()(64bit)
root:            Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (oracle-linux-latest-7-64)
root:                Not found
root:            Available: ImageMagick-6.7.8.9-15.el7_2.x86_64 (oracle-linux-latest-7-64)
root:                libMagickCore.so.5()(64bit)
root:            Available: ImageMagick-6.7.8.9-16.el7_6.x86_64 (oracle-linux-latest-7-64)
root:                libMagickCore.so.5()(64bit)`

The new package provides:

`/usr/lib64/libMagickCore-6.Q16.so
/usr/lib64/libMagickCore-6.Q16.so.6
/usr/lib64/libMagickCore-6.Q16.so.6.0.0
/usr/lib64/libMagickWand-6.Q16.so
/usr/lib64/libMagickWand-6.Q16.so.6
/usr/lib64/libMagickWand-6.Q16.so.6.0.0`

Thanks,

-stefan

Edit: Formatting is all screwed up and I dont' know why

**Comment by EsbenSunddal** [comment]
I have the same problem - yum update is blocked :(

### yum update
     --> Finished Dependency Resolution
     --> Running transaction check
     ---> Package ImageMagick.x86_64 0:6.7.8.9-18.el7 will be updated
     --> Processing Dependency: libMagickCore.so.5()(64bit) for package: php70w-pecl-imagick-3.4.3-1.w7.x86_64
     --> Processing Dependency: libMagickWand.so.5()(64bit) for package: php70w-pecl-imagick-3.4.3-1.w7.x86_64
     ---> Package kernel.x86_64 0:3.10.0-1062.9.1.el7 will be erased
     --> Finished Dependency Resolution
     Error: Package: php70w-pecl-imagick-3.4.3-1.w7.x86_64 (@webtatic)
                Requires: libMagickCore.so.5()(64bit)
                Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@base)
                    libMagickCore.so.5()(64bit)
                Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (base)
                    Not found
     Error: Package: php70w-pecl-imagick-3.4.3-1.w7.x86_64 (@webtatic)
                Requires: libMagickWand.so.5()(64bit)
                Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@base)
                    libMagickWand.so.5()(64bit)
                Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (base)
                    Not found
     



Thank you!

**Comment by andytson** [comment]
PHP 7.0 is EOL, so wont be receiving a fix

The issue is not present in PHP 7.2 packages after an update earlier this month

**Comment by EsbenSunddal** [comment]
The problem is we need PHP 7.0 for some sites, that can't be upgraded.
